# Default values for notification-slack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ibmstocktrader/notification-slack
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort

ingress:
  enabled: true
  path: /notification
