# Default values for messaging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ibmstocktrader/messaging
  tag: latest
  pullPolicy: IfNotPresent
