apiVersion: v1
kind: Service
metadata:
  name: trader-service
  labels:
    app: {{ template "trader.name" . }}
    chart: {{ template "trader.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
      nodePort: 32388
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 32389
  selector:
    app: {{ template "trader.name" . }}
    release: {{ .Release.Name }}
