{{- if .Values.ingress.enabled -}}
{{- $fullName := include "stock-quote.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "stock-quote.name" . }}
    chart: {{ template "stock-quote.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /stock-quote/.*
        backend:
          serviceName: stock-quote-service
          servicePort: 9080
{{- end }}
