apiVersion: v1
kind: Service
metadata:
  name: stock-quote-service
  labels:
    app: {{ template "stock-quote.name" . }}
    chart: {{ template "stock-quote.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: {{ template "stock-quote.name" . }}
    release: {{ .Release.Name }}
