# Default values for portfolio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ibmstocktrader/portfolio
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort

ingress:
  enabled: true
