# Default values for stocktrader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

appInClusterNamespace: default

targetCluster:
  labelSelector:
    matchLabels:
      cloud: "IBM"
      vendor: "ICP"
      datacenter: "Raleigh"
      region: "US"
      owner: "marketing"
  resourceSelector:
    type: cpu
