apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "portfolio.fullname" . }}
  labels:
    app: {{ template "portfolio.name" . }}
    chart: {{ template "portfolio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    solution: "stack-trader"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "portfolio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "portfolio.name" . }}
        release: {{ .Release.Name }}
        solution: stock-trader
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JDBC_HOST
              valueFrom:
                secretKeyRef:
                  name: db2
                  key: host
            - name: JDBC_PORT
              valueFrom:
                secretKeyRef:
                  name: db2
                  key: port
            - name: JDBC_DB
              valueFrom:
                secretKeyRef:
                  name: db2
                  key: db
            - name: JDBC_ID
              valueFrom:
                secretKeyRef:
                  name: db2
                  key: id
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db2
                  key: pwd
            - name: MQ_ID
              valueFrom:
                secretKeyRef:
                  name: mq
                  key: id
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mq
                  key: pwd
            - name: MQ_HOST
              valueFrom:
                secretKeyRef:
                  name: mq
                  key: host
            - name: MQ_PORT
              valueFrom:
                secretKeyRef:
                  name: mq
                  key: port
            - name: MQ_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: mq
                  key: channel
            - name: MQ_QUEUE_MANAGER
              valueFrom:
                secretKeyRef:
                  name: mq
                  key: queue-manager
            - name: MQ_QUEUE
              valueFrom:
                 secretKeyRef:
                   name: mq
                   key: queue
            - name: WATSON_URL
              valueFrom:
                secretKeyRef:
                  name: watson
                  key: url
            - name: WATSON_ID
              valueFrom:
                secretKeyRef:
                  name: watson
                  key: id
            - name: WATSON_PWD
              valueFrom:
                secretKeyRef:
                  name: watson
                  key: pwd
            - name: ODM_URL
              valueFrom:
                secretKeyRef:
                  name: odm
                  key: url
            - name: ODM_ID
              valueFrom:
                secretKeyRef:
                  name: odm
                  key: id
            - name: ODM_PWD
              valueFrom:
                secretKeyRef:
                  name: odm
                  key: pwd
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: audience
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: issuer
          ports:
            - containerPort: 9080
            - containerPort: 9443

